name: Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: npm distribution channel
        required: true
        default: latest
        type: choice
        options:
          - latest
          - next

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: AntelopeJS/.github/.github/workflows/release-npm-public.yml@main
    with:
      channel: ${{ inputs.channel }}
      install-core: true
    secrets: inherit
